(function(g){
"use strict";
const L=g.ZebjusCircuitLibrary;if(!L)throw new Error("component-library.js must load first");
const STORAGE="zebjus.lab.circuit.v2",LEGACY_STORAGE="zebjus.lab.circuit.v1",CODE_KEY="zebjus.lab.code",CHANNEL="zebjus-circuit-design-v2";
const designListeners=new Set();let designChannel=null;
function publishDesign(d){try{designChannel?.postMessage({type:"design",design:d})}catch(_){}}
function notifyDesign(d){const next=normalizeDesign(d);for(const fn of designListeners)try{fn(clone(next))}catch(_){}}
function onDesignChange(fn){if(typeof fn!=="function")return()=>{};designListeners.add(fn);return()=>designListeners.delete(fn);}
try{if(g.document&&typeof g.BroadcastChannel==="function"){designChannel=new g.BroadcastChannel(CHANNEL);designChannel.addEventListener("message",e=>{if(e.data?.type==="design"&&e.data.design)notifyDesign(e.data.design)})}g.addEventListener?.("storage",e=>{if((e.key===STORAGE||e.key===LEGACY_STORAGE)&&e.newValue)try{notifyDesign(JSON.parse(e.newValue))}catch(_){}})}catch(_){}
const STATIC={gpioOut:[...L.OUTPUT_PINS],gpioIn:[...L.DIGITAL_INPUT_PINS,12],adc1:[...L.ADC_PINS],counterPins:[...L.COUNTER_PINS],i2cBuses:2,uartPorts:[1,2],spiBuses:[1,2],counterSlots:8,tm1637Slots:4,lcd1602Slots:4,source:"firmware-v2.4.0-profile"};
let CAPS=JSON.parse(JSON.stringify(STATIC));
let OUT=new Set(CAPS.gpioOut),ADC=new Set(CAPS.adc1),DIN=new Set(CAPS.gpioIn),ECHO=new Set([...CAPS.gpioIn,12]),CNT=new Set(CAPS.counterPins);
const I2C_PAIRS=[[21,22],[25,26],[18,19],[16,17],[32,33],[13,14]];
const OUT_ORDER=[13,14,18,19,16,17,25,26,27,32,33,4,21,22,23];
const IN_ORDER=[34,35,36,39,32,33,19,18,16,17,14,13,4,21,22,23,25,26,27,12];
const ADC_ORDER=[34,35,36,39,32,33];
const CNT_ORDER=[34,35,32,33,14,27,26,25,4,13,16,17,18,19,21,22,23];
function clone(x){return JSON.parse(JSON.stringify(x));}
function setBridgeCapabilities(info={}){CAPS={...STATIC,source:"connected-kit",...Object.fromEntries(Object.entries(info||{}).filter(([,v])=>v!=null))};CAPS.gpioOut=Array.isArray(CAPS.gpioOut)?CAPS.gpioOut:STATIC.gpioOut;CAPS.gpioIn=Array.isArray(CAPS.gpioIn)?CAPS.gpioIn:STATIC.gpioIn;CAPS.adc1=Array.isArray(CAPS.adc1)?CAPS.adc1:STATIC.adc1;CAPS.counterPins=Array.isArray(CAPS.counterPins)?CAPS.counterPins:STATIC.counterPins;CAPS.uartPorts=Array.isArray(CAPS.uartPorts)?CAPS.uartPorts:STATIC.uartPorts;CAPS.spiBuses=Array.isArray(CAPS.spiBuses)?CAPS.spiBuses:STATIC.spiBuses;OUT=new Set(CAPS.gpioOut);ADC=new Set(CAPS.adc1);DIN=new Set(CAPS.gpioIn);ECHO=new Set([...CAPS.gpioIn,12]);CNT=new Set(CAPS.counterPins);return getCapabilities();}
function getCapabilities(){return clone(CAPS);}
function propDefaults(m){const p={};for(const s of (m?.properties||[]))p[s.key]=clone(s.default);if(m?.defaultAddress!=null&&p.address==null)p.address=m.defaultAddress;return p;}
function newDesign(){return {version:2,name:"Circuit 1",width:2400,height:1600,board:{x:940,y:420},components:[],connections:[],updatedAt:new Date().toISOString()};}
function normalizeDesign(raw){const d=raw&&typeof raw==="object"?clone(raw):newDesign();d.version=2;d.name=String(d.name||"Circuit 1");d.width=Math.max(1400,Number(d.width)||2400);d.height=Math.max(900,Number(d.height)||1600);const bx=Number(d.board?.x),by=Number(d.board?.y);d.board={x:Number.isFinite(bx)?bx:940,y:Number.isFinite(by)?by:420};d.components=Array.isArray(d.components)?d.components:[];d.connections=Array.isArray(d.connections)?d.connections:[];for(const c of d.components){const m=L.BY_TYPE[c.type];c.x=Math.max(0,Number(c.x)||0);c.y=Math.max(0,Number(c.y)||0);c.rotation=((Number(c.rotation)||0)%360+360)%360;c.flipX=!!c.flipX;c.flipY=!!c.flipY;c.properties={...propDefaults(m),...(c.properties||{})};}return d;}
function nextId(d,type){let i=1;while(d.components.some(c=>c.id===`${type}${i}`))i++;return `${type}${i}`;}
function addComponent(d,type,x=180,y=180){const m=L.BY_TYPE[type];if(!m)throw new Error(`Unknown component ${type}`);const c={id:nextId(d,type),type,x:Number(x)||0,y:Number(y)||0,rotation:0,flipX:false,flipY:false,properties:propDefaults(m)};d.components.push(c);d.updatedAt=new Date().toISOString();return c;}
function removeComponent(d,id){d.components=d.components.filter(c=>c.id!==id);d.connections=d.connections.filter(w=>w.componentId!==id);d.updatedAt=new Date().toISOString();}
function connectionFor(d,id,port){return d.connections.find(w=>w.componentId===id&&w.port===port)||null;}
function boardInfo(id){return L.BY_PIN[id]||null;}
function componentMeta(c){return c?L.BY_TYPE[c.type]||null:null;}
function propertySchema(c,key){return componentMeta(c)?.properties?.find(p=>p.key===key)||null;}
function setProperty(d,id,key,value){const c=d.components.find(x=>x.id===id);if(!c)throw new Error("Component not found");const s=propertySchema(c,key);if(!s)throw new Error(`Property ${key} is not supported by ${c.type}`);let v=value;if(s.type==="number"||s.type==="hex"){v=Number(v);if(!Number.isFinite(v))throw new Error(`${s.label} must be numeric`);if(s.min!=null&&v<s.min)throw new Error(`${s.label} must be ≥ ${s.min}`);if(s.max!=null&&v>s.max)throw new Error(`${s.label} must be ≤ ${s.max}`);}else if(s.type==="checkbox")v=!!v;else if(s.type==="select"){const opts=s.options||[];const hit=opts.find(o=>String(o)===String(v));if(hit===undefined)throw new Error(`${s.label} has an invalid value`);v=hit;}c.properties[key]=v;d.updatedAt=new Date().toISOString();return v;}
function i2cBus(c){return c?.type==="OLED"?0:(Number(c?.properties?.bus)===1?1:0);}
function spiBus(c){const v=c?.properties?.bus;return Number(v)===2?2:1;}
function compatible(port,b){if(!port||!b)return false;if(port.kind==="power")return b.power===port.power;if(port.kind==="gnd")return b.power==="GND";if(b.gpio==null)return false;const p=b.gpio;switch(port.kind){case"adc":return ADC.has(p);case"digitalIn":return DIN.has(p)&&p!==12;case"counterIn":return CNT.has(p);case"echoIn":return ECHO.has(p);case"digitalOut":case"pwmOut":case"bidir":case"i2cSda":case"i2cScl":case"uartRx":case"spiSck":case"spiMosi":case"spiCs":return OUT.has(p);case"uartTx":case"spiMiso":return ECHO.has(p);default:return false;}}
function shareKey(c,port){if(port.kind==="i2cSda"||port.kind==="i2cScl")return `i2c${i2cBus(c)}:${port.kind}`;if(port.kind==="spiSck"||port.kind==="spiMiso"||port.kind==="spiMosi")return `spi${spiBus(c)}:${port.kind}`;return null;}
function occupied(d){const map=new Map();for(const w of d.connections){const b=boardInfo(w.boardPin);if(!b||b.gpio==null)continue;const c=d.components.find(x=>x.id===w.componentId),m=componentMeta(c),p=m?.ports.find(x=>x.name===w.port),sk=p?shareKey(c,p):null;if(!map.has(b.gpio))map.set(b.gpio,[]);map.get(b.gpio).push({w,c,p,share:sk});}return map;}
function canUsePin(d,c,port,boardPin){const b=boardInfo(boardPin);if(!compatible(port,b))return {ok:false,reason:`${port.label} requires ${port.kind}`};if(b.gpio==null)return {ok:true};const occ=(occupied(d).get(b.gpio)||[]).filter(o=>!(o.w.componentId===c.id&&o.w.port===port.name));if(!occ.length)return {ok:true};const sk=shareKey(c,port);if(sk&&occ.every(o=>o.share===sk))return {ok:true,shared:true};return {ok:false,reason:`${boardPin} is already used by ${occ.map(o=>o.w.componentId+"."+o.w.port).join(", ")}`};}
function connect(d,componentId,portName,boardPin){const c=d.components.find(x=>x.id===componentId);if(!c)throw new Error("Component not found");const m=componentMeta(c),port=m?.ports.find(p=>p.name===portName);if(!port)throw new Error("Port not found");const ck=canUsePin(d,c,port,boardPin);if(!ck.ok)throw new Error(ck.reason);d.connections=d.connections.filter(w=>!(w.componentId===componentId&&w.port===portName));d.connections.push({id:`w_${componentId}_${portName}`,componentId,port:portName,boardPin,kind:port.kind});d.updatedAt=new Date().toISOString();return d.connections[d.connections.length-1];}
function disconnect(d,wireId){d.connections=d.connections.filter(w=>w.id!==wireId);d.updatedAt=new Date().toISOString();}
function busPins(d,prefix,bus){const out={};for(const w of d.connections){const c=d.components.find(x=>x.id===w.componentId);if(!c)continue;const p=componentMeta(c)?.ports.find(x=>x.name===w.port),b=boardInfo(w.boardPin);if(!p||b?.gpio==null)continue;if(prefix==="i2c"&&i2cBus(c)===bus&&(p.kind==="i2cSda"||p.kind==="i2cScl"))out[p.kind]=b.gpio;if(prefix==="spi"&&spiBus(c)===bus&&["spiSck","spiMiso","spiMosi"].includes(p.kind))out[p.kind]=b.gpio;}return out;}
function firstPin(d,c,port,candidates){for(const p of candidates){if(p===12&&port.kind!=="echoIn"&&port.kind!=="uartTx"&&port.kind!=="spiMiso")continue;const r=canUsePin(d,c,port,`GPIO${p}`);if(r.ok)return `GPIO${p}`;}return null;}
function allocateI2CPair(d,c){const bus=i2cBus(c),existing=busPins(d,"i2c",bus);if(existing.i2cSda!=null&&existing.i2cScl!=null)return [existing.i2cSda,existing.i2cScl];const sda=componentMeta(c).ports.find(p=>p.kind==="i2cSda"),scl=componentMeta(c).ports.find(p=>p.kind==="i2cScl");for(const q of I2C_PAIRS){if(canUsePin(d,c,sda,`GPIO${q[0]}`).ok&&canUsePin(d,c,scl,`GPIO${q[1]}`).ok)return q;}return null;}
function allocateSPITriplet(d,c){const bus=spiBus(c),e=busPins(d,"spi",bus);if(e.spiSck!=null&&e.spiMiso!=null&&e.spiMosi!=null)return [e.spiSck,e.spiMiso,e.spiMosi];const m=componentMeta(c),sck=m.ports.find(p=>p.kind==="spiSck"),miso=m.ports.find(p=>p.kind==="spiMiso"),mosi=m.ports.find(p=>p.kind==="spiMosi");for(const a of OUT_ORDER){if(!canUsePin(d,c,sck,`GPIO${a}`).ok)continue;for(const b of IN_ORDER){if(b===a||!canUsePin(d,c,miso,`GPIO${b}`).ok)continue;for(const cc of OUT_ORDER){if(cc===a||cc===b||!canUsePin(d,c,mosi,`GPIO${cc}`).ok)continue;return [a,b,cc];}}}return null;}
function autoWireComponent(d,id){const c=d.components.find(x=>x.id===id);if(!c)throw new Error("Component not found");const m=componentMeta(c);if(!m)throw new Error("Component metadata missing");let i2cPair=null,spiTriple=null;if(m.ports.some(p=>p.kind==="i2cSda"||p.kind==="i2cScl"))i2cPair=allocateI2CPair(d,c);if(m.ports.some(p=>p.kind==="spiSck"))spiTriple=allocateSPITriplet(d,c);
for(const port of m.ports){if(connectionFor(d,id,port.name))continue;let bp=null;if(port.kind==="power")bp=port.power==="12V"?"12V":port.power==="5V"?"5V_OUT":"3V3_OUT";else if(port.kind==="gnd")bp="PWR_GND";else if(port.kind==="i2cSda")bp=i2cPair?`GPIO${i2cPair[0]}`:null;else if(port.kind==="i2cScl")bp=i2cPair?`GPIO${i2cPair[1]}`:null;else if(port.kind==="spiSck")bp=spiTriple?`GPIO${spiTriple[0]}`:null;else if(port.kind==="spiMiso")bp=spiTriple?`GPIO${spiTriple[1]}`:null;else if(port.kind==="spiMosi")bp=spiTriple?`GPIO${spiTriple[2]}`:null;else if(port.kind==="adc")bp=firstPin(d,c,port,ADC_ORDER);else if(port.kind==="counterIn")bp=firstPin(d,c,port,CNT_ORDER);else if(port.kind==="echoIn")bp=firstPin(d,c,port,[34,35,36,39,19,18,17,16,33,32,27,26,25,23,22,21,14,13,4,12]);else if(port.kind==="digitalIn"||port.kind==="uartTx"||port.kind==="spiMiso")bp=firstPin(d,c,port,IN_ORDER);else bp=firstPin(d,c,port,OUT_ORDER);if(bp)connect(d,id,port.name,bp);else if(!port.optional)throw new Error(`${c.type}: no compatible free pin for ${port.label}`);}return c;}
function autoWireAll(d){const errors=[];for(const c of d.components){try{autoWireComponent(d,c.id);}catch(e){errors.push({componentId:c.id,message:String(e.message||e)});}}return errors;}
function allocateUARTPorts(d){const arr=d.components.filter(c=>c.type==="UART"||c.type==="GPS"),allowed=(CAPS.uartPorts||[1,2]).map(Number),used=new Map(),map=new Map(),errors=[];for(const c of arr){const v=c.properties?.port;if(v!=="auto"&&v!=null&&v!==""){const p=Number(v);if(!allowed.includes(p))errors.push(`${c.id}: UART port ${p} is unavailable`);else if(used.has(p))errors.push(`${c.id}: UART port ${p} is already assigned to ${used.get(p)}`);else{used.set(p,c.id);map.set(c.id,p);}}}for(const c of arr){if(map.has(c.id))continue;const p=allowed.find(x=>!used.has(x));if(p==null)errors.push(`${c.id}: only ${allowed.length} UART ports are available`);else{used.set(p,c.id);map.set(c.id,p);}}return {map,errors};}
function allocateSPIBuses(d){const allowed=(CAPS.spiBuses||[1,2]).map(Number),map=new Map(),errors=[];for(const c of d.components.filter(c=>c.type==="SPI")){const raw=c.properties?.bus,p=raw==="auto"||raw==null?allowed[0]:Number(raw);if(!allowed.includes(p))errors.push(`${c.id}: SPI bus ${p} is unavailable`);else map.set(c.id,p);}return {map,errors};}
function addressOf(c){const n=Number(c?.properties?.address);return Number.isFinite(n)?n:null;}
function validateProperties(c,issues){const m=componentMeta(c);for(const s of (m?.properties||[])){const v=c.properties?.[s.key];if(s.type==="number"||s.type==="hex"){const n=Number(v);if(!Number.isFinite(n)||(s.min!=null&&n<s.min)||(s.max!=null&&n>s.max))issues.push({level:"error",componentId:c.id,message:`${m.label}: invalid ${s.label}`});}else if(s.type==="select"&&!((s.options||[]).some(o=>String(o)===String(v))))issues.push({level:"error",componentId:c.id,message:`${m.label}: invalid ${s.label}`});}}
function validateDesign(d){const issues=[],seen=new Map(),i2cMap=new Map(),spiMap=new Map();for(const c of d.components){const m=componentMeta(c);if(!m){issues.push({level:"error",componentId:c.id,message:`Unknown component ${c.type}`});continue;}validateProperties(c,issues);for(const p of m.ports){const w=connectionFor(d,c.id,p.name);if(!w){if(!p.optional)issues.push({level:"error",componentId:c.id,port:p.name,message:`${m.label}: ${p.label} is not connected`});continue;}const b=boardInfo(w.boardPin);if(!compatible(p,b))issues.push({level:"error",componentId:c.id,port:p.name,message:`${m.label} ${p.label} cannot connect to ${w.boardPin}`});if(b?.bootSensitive)issues.push({level:"warning",componentId:c.id,port:p.name,message:`GPIO12 is boot-sensitive; use it only when intentionally required.`});if(b?.gpio!=null){const sk=shareKey(c,p);if(!seen.has(b.gpio))seen.set(b.gpio,[]);seen.get(b.gpio).push({c,p,w,sk});if(p.kind==="i2cSda"||p.kind==="i2cScl"){const k=i2cBus(c);if(!i2cMap.has(k))i2cMap.set(k,{sda:new Set(),scl:new Set(),addresses:new Map()});i2cMap.get(k)[p.kind==="i2cSda"?"sda":"scl"].add(b.gpio);}if(["spiSck","spiMiso","spiMosi"].includes(p.kind)){const k=spiBus(c);if(!spiMap.has(k))spiMap.set(k,{sck:new Set(),miso:new Set(),mosi:new Set()});spiMap.get(k)[p.kind.replace("spi","").toLowerCase()].add(b.gpio);}}}
if(m.resource==="i2c"&&addressOf(c)!=null){const bus=i2cBus(c),key=`${bus}:${addressOf(c)}`;const prev=i2cMap.get(bus)?.addresses||new Map();if(!i2cMap.has(bus))i2cMap.set(bus,{sda:new Set(),scl:new Set(),addresses:new Map()});const addresses=i2cMap.get(bus).addresses;if(addresses.has(key))issues.push({level:"error",componentId:c.id,message:`I²C bus ${bus} address ${hex(addressOf(c))} is already used by ${addresses.get(key)}`});else addresses.set(key,c.id);}
for(const msg of (m.warnings||[]))issues.push({level:"warning",componentId:c.id,message:msg});}
for(const [gpio,arr] of seen){if(arr.length<2)continue;const shares=arr.map(x=>x.sk);if(!(shares.every(Boolean)&&new Set(shares).size===1))issues.push({level:"error",message:`GPIO${gpio} conflict: ${arr.map(x=>x.c.id+"."+x.p.name).join(", ")}`});}
for(const [bus,x] of i2cMap){if(x.sda.size>1||x.scl.size>1)issues.push({level:"error",message:`I²C bus ${bus} must share one SDA/SCL pair across all devices.`});}
for(const [bus,x] of spiMap){if(x.sck.size>1||x.miso.size>1||x.mosi.size>1)issues.push({level:"error",message:`SPI bus ${bus} must share SCK/MISO/MOSI; use a different CS per device.`});}
const uart=allocateUARTPorts(d);for(const e of uart.errors)issues.push({level:"error",message:e});const spi=allocateSPIBuses(d);for(const e of spi.errors)issues.push({level:"error",message:e});
const counts={};for(const c of d.components)counts[c.type]=(counts[c.type]||0)+1;if((counts.SingleLED||0)>15)issues.push({level:"error",message:"Single LED supports a maximum of 15 numbered outputs (LED1…LED15)."});if((counts.OLED||0)>1)issues.push({level:"error",message:"Firmware supports one active OLED display at a time."});if((counts.TM1637||0)>Number(CAPS.tm1637Slots||4))issues.push({level:"error",message:`TM1637 limit exceeded: firmware provides ${CAPS.tm1637Slots||4} slots.`});if((counts.LCD1602||0)>Number(CAPS.lcd1602Slots||4))issues.push({level:"error",message:`LCD1602 limit exceeded: firmware provides ${CAPS.lcd1602Slots||4} slots.`});const counterCount=(counts.CounterInput||0)+(counts.FlowSensor||0)+(counts.RPMSensor||0);if(counterCount>Number(CAPS.counterSlots||8))issues.push({level:"error",message:`Counter-input limit exceeded: ${counterCount}/${CAPS.counterSlots||8} slots.`});
for(const [t,n] of Object.entries(counts)){const m=L.BY_TYPE[t];if(m?.maxInstances&&n>m.maxInstances&&!["CounterInput","FlowSensor","RPMSensor","UART","GPS"].includes(t))issues.push({level:"error",message:`${m.label} limit exceeded: ${n}/${m.maxInstances}.`});}
return issues;}
function gpio(d,cid,port,def=null){const w=connectionFor(d,cid,port),b=w&&boardInfo(w.boardPin);return b&&b.gpio!=null?b.gpio:def;}
function hex(n){return `0x${Number(n).toString(16).toUpperCase()}`;}
function boolPy(v){return v?"True":"False";}
function codeContext(d){return {uart:allocateUARTPorts(d).map,spi:allocateSPIBuses(d).map,singleLed:new Map(d.components.filter(c=>c.type==="SingleLED").map((c,i)=>[c.id,i+1]))};}
function ctor(c,d,ctx){const t=c.type,id=c.id.replace(/[^A-Za-z0-9_]/g,"_"),v=id.charAt(0).toLowerCase()+id.slice(1),p=c.properties||{},addr=addressOf(c);switch(t){
case"SingleLED":{const slot=ctx.singleLed.get(c.id);return {imp:`LED${slot}`,line:`${v} = LED${slot}(${gpio(d,c.id,"SIG")})`};}
case"RGBLED":return {imp:"RGBLED",line:`${v} = RGBLED(${gpio(d,c.id,"R")}, ${gpio(d,c.id,"G")}, ${gpio(d,c.id,"B")})`};
case"TM1637":return {imp:t,line:`${v} = TM1637(clk=${gpio(d,c.id,"CLK")}, dio=${gpio(d,c.id,"DIO")}, brightness=${Number(p.brightness??6)})`};
case"LCD1602":return {imp:t,line:`${v} = LCD1602(sda=${gpio(d,c.id,"SDA")}, scl=${gpio(d,c.id,"SCL")}, address=${hex(addr??0x27)}, bus=${i2cBus(c)})`};
case"OLED":return {imp:t,line:`${v} = OLED(sda=${gpio(d,c.id,"SDA")}, scl=${gpio(d,c.id,"SCL")}, address=${hex(addr??0x3C)})`};
case"DHT11":return {imp:t,line:`${v} = DHT11(pin=${gpio(d,c.id,"DATA")})`};
case"Ultrasonic":return {imp:t,line:`${v} = Ultrasonic(trig=${gpio(d,c.id,"TRIG")}, echo=${gpio(d,c.id,"ECHO")})`};
case"Potentiometer":case"AnalogInput":return {imp:t,line:`${v} = ${t}(pin=${gpio(d,c.id,"AO")})`};
case"Switch":case"DigitalInput":return {imp:t,line:`${v} = ${t}(pin=${gpio(d,c.id,"SIG")})`};
case"RotaryEncoder":return {imp:t,line:`${v} = RotaryEncoder(clk=${gpio(d,c.id,"CLK")}, dt=${gpio(d,c.id,"DT")}, switch=${gpio(d,c.id,"SW","None")})`};
case"DigitalOutput":case"GPIOInput":case"PulseInput":case"PulseOutput":return {imp:t,line:`${v} = ${t}(pin=${gpio(d,c.id,"SIG")})`};
case"CounterInput":return {imp:t,line:`${v} = CounterInput(pin=${gpio(d,c.id,"SIG")}, edge=${JSON.stringify(String(p.edge||"rising"))}, pullup=${boolPy(!!p.pullup)})`};
case"Relay":return {imp:t,line:`${v} = Relay(pin=${gpio(d,c.id,"IN")})`};
case"ADC":case"LDR":case"SoilMoisture":case"GasSensor":case"VoltageSensor":case"SoundSensor":case"RainSensor":case"WaterLevelSensor":case"Thermistor":return {imp:t,line:`${v} = ${t}(pin=${gpio(d,c.id,"AO")})`};
case"PWM":return {imp:t,line:`${v} = PWM(pin=${gpio(d,c.id,"PWM")}, frequency=${Number(p.frequency??1000)}, resolution=${Number(p.resolution??8)})`};
case"PWMServo":return {imp:t,line:`${v} = PWMServo(pin=${gpio(d,c.id,"PWM")}, min_us=${Number(p.min_us??500)}, max_us=${Number(p.max_us??2500)}, frequency=${Number(p.frequency??50)})`};
case"MotorDriver":return {imp:t,line:`${v} = MotorDriver(in1=${gpio(d,c.id,"IN1")}, in2=${gpio(d,c.id,"IN2")}, pwm_pin=${gpio(d,c.id,"PWM")}, frequency=${Number(p.frequency??18000)})`};
case"I2C":return {imp:t,line:`${v} = I2C(sda=${gpio(d,c.id,"SDA")}, scl=${gpio(d,c.id,"SCL")}, frequency=${Number(p.frequency??400000)}, bus=${i2cBus(c)})`};
case"I2CDevice":return {imp:t,line:`${v} = I2CDevice(address=${hex(addr??0x40)}, sda=${gpio(d,c.id,"SDA")}, scl=${gpio(d,c.id,"SCL")}, frequency=${Number(p.frequency??400000)}, bus=${i2cBus(c)})`};
case"UART":{const port=ctx.uart.get(c.id);return {imp:t,line:`${v} = UART(rx=${gpio(d,c.id,"TX")}, tx=${gpio(d,c.id,"RX")}, baud=${Number(p.baud??9600)}, port=${port})`};}
case"GPS":{const port=ctx.uart.get(c.id);return {imp:t,line:`${v} = GPS(rx=${gpio(d,c.id,"TX")}, tx=${gpio(d,c.id,"RX")}, baud=${Number(p.baud??9600)}, port=${port})`};}
case"SPI":{const bus=ctx.spi.get(c.id)||spiBus(c);return {imp:t,line:`${v} = SPI(sck=${gpio(d,c.id,"SCK")}, miso=${gpio(d,c.id,"MISO")}, mosi=${gpio(d,c.id,"MOSI")}, cs=${gpio(d,c.id,"CS")}, frequency=${Number(p.frequency??1000000)}, mode=${Number(p.mode??0)}, bus=${bus}, lsb_first=${boolPy(!!p.lsb_first)}, active_low=${boolPy(p.active_low!==false)})`};}
case"HardwareTransaction":return {imp:t,line:`${v} = HardwareTransaction(${JSON.stringify(v)})`};
case"MPU6050":return {imp:t,line:`${v} = MPU6050(sda=${gpio(d,c.id,"SDA")}, scl=${gpio(d,c.id,"SCL")}, address=${hex(addr??0x68)}, bus=${i2cBus(c)})`};
case"PIRSensor":case"ReedSwitch":case"TouchSensor":case"FlameSensor":return {imp:t,line:`${v} = ${t}(pin=${gpio(d,c.id,"SIG")})`};
case"FlowSensor":return {imp:t,line:`${v} = FlowSensor(pin=${gpio(d,c.id,"SIG")}, pulses_per_liter=${Number(p.pulses_per_liter??450)}, edge=${JSON.stringify(String(p.edge||"rising"))}, pullup=${boolPy(!!p.pullup)})`};
case"RPMSensor":return {imp:t,line:`${v} = RPMSensor(pin=${gpio(d,c.id,"SIG")}, pulses_per_revolution=${Number(p.pulses_per_revolution??1)}, edge=${JSON.stringify(String(p.edge||"rising"))}, pullup=${boolPy(!!p.pullup)})`};
case"Buzzer":return {imp:t,line:`${v} = Buzzer(pin=${gpio(d,c.id,"SIG")}, frequency=${Number(p.frequency??1000)})`};
case"Joystick":return {imp:t,line:`${v} = Joystick(x_pin=${gpio(d,c.id,"X")}, y_pin=${gpio(d,c.id,"Y")}, switch_pin=${gpio(d,c.id,"SW","None")})`};
case"DCMotor":case"TTGearMotor":return {imp:t,line:`${v} = ${t}(in1=${gpio(d,c.id,"IN1")}, in2=${gpio(d,c.id,"IN2")}, pwm_pin=${gpio(d,c.id,"PWM")}, frequency=${Number(p.frequency??18000)})`};
case"StepperMotor":return {imp:t,line:`${v} = StepperMotor(in1=${gpio(d,c.id,"IN1")}, in2=${gpio(d,c.id,"IN2")}, in3=${gpio(d,c.id,"IN3")}, in4=${gpio(d,c.id,"IN4")}, steps_per_revolution=${Number(p.steps_per_revolution??2048)})`};
case"BLDCESC":return {imp:t,line:`${v} = BLDCESC(pin=${gpio(d,c.id,"PWM")}, frequency=${Number(p.frequency??50)})`};
case"FanMotor":case"VibrationMotor":return {imp:t,line:`${v} = ${t}(pin=${gpio(d,c.id,"PWM")})`};
case"WaterPump":case"Solenoid":case"LaserModule":return {imp:t,line:`${v} = ${t}(pin=${gpio(d,c.id,"SIG")})`};
case"PCA9685":return {imp:t,line:`${v} = PCA9685(sda=${gpio(d,c.id,"SDA")}, scl=${gpio(d,c.id,"SCL")}, address=${hex(addr??0x40)}, bus=${i2cBus(c)}, frequency=${Number(p.frequency??50)})`};
case"LSM6DS3":case"BME280":case"BMP280":case"ADXL345":case"BH1750":case"VL53L0X":case"DS3231":return {imp:t,line:`${v} = ${t}(sda=${gpio(d,c.id,"SDA")}, scl=${gpio(d,c.id,"SCL")}, address=${hex(addr)}, bus=${i2cBus(c)})`};
case"DS18B20":return {imp:t,line:`${v} = DS18B20(pin=${gpio(d,c.id,"DATA")})`};
case"IRObstacle":case"IRReceiver":case"LineSensor":case"TiltSensor":return {imp:t,line:`${v} = ${t}(pin=${gpio(d,c.id,"SIG")})`};
case"HallSensor":case"PhotoInterrupt":return {imp:t,line:`${v} = ${t}(pin=${gpio(d,c.id,"SIG")})`};
case"FlexSensor":case"CurrentSensor":return {imp:t,line:`${v} = ${t}(pin=${gpio(d,c.id,"AO")})`};
case"HX711":return {imp:t,line:`${v} = HX711(data_pin=${gpio(d,c.id,"DT")}, clock_pin=${gpio(d,c.id,"SCK")}, scale=${Number(p.scale??1)})`};
case"RC522":case"MicroSD":return {imp:t,line:`${v} = ${t}(sck=${gpio(d,c.id,"SCK")}, miso=${gpio(d,c.id,"MISO")}, mosi=${gpio(d,c.id,"MOSI")}, cs=${gpio(d,c.id,"CS")}, bus=${spiBus(c)})`};
case"MAX7219":return {imp:t,line:`${v} = MAX7219(sck=${gpio(d,c.id,"SCK")}, miso=${gpio(d,c.id,"MISO","None")}, mosi=${gpio(d,c.id,"MOSI")}, cs=${gpio(d,c.id,"CS")}, bus=${spiBus(c)}, brightness=${Number(p.brightness??8)})`};
case"LoRaSX1278":return {imp:t,line:`${v} = LoRaSX1278(sck=${gpio(d,c.id,"SCK")}, miso=${gpio(d,c.id,"MISO")}, mosi=${gpio(d,c.id,"MOSI")}, cs=${gpio(d,c.id,"CS")}, bus=${spiBus(c)}, frequency=${Number(p.frequency??433000000)})`};
case"MCP2515":return {imp:t,line:`${v} = MCP2515(sck=${gpio(d,c.id,"SCK")}, miso=${gpio(d,c.id,"MISO")}, mosi=${gpio(d,c.id,"MOSI")}, cs=${gpio(d,c.id,"CS")}, interrupt_pin=${gpio(d,c.id,"INT")}, bus=${spiBus(c)}, bitrate=${Number(p.bitrate??500000)})`};
case"NeoPixel":return {imp:t,line:`${v} = NeoPixel(pin=${gpio(d,c.id,"DATA")}, count=${Number(p.count??8)})`};
case"Keypad4x4":return {imp:t,line:`${v} = Keypad4x4(rows=[${["R1","R2","R3","R4"].map(x=>gpio(d,c.id,x)).join(", ")}], cols=[${["C1","C2","C3","C4"].map(x=>gpio(d,c.id,x)).join(", ")}])`};
case"SevenSegment":return {imp:t,line:`${v} = SevenSegment(pins=[${["A","B","C","D","E","F","G","DP"].map(x=>gpio(d,c.id,x)).join(", ")}])`};
default:throw new Error(`No code generator for ${t}`);}}
function generatePython(d){const errs=validateDesign(d).filter(x=>x.level==="error");if(errs.length)throw new Error(errs.map(x=>x.message).join("; "));const imports=[],lines=[],ctx=codeContext(d);for(const c of d.components){const x=ctor(c,d,ctx);if(!imports.includes(x.imp))imports.push(x.imp);lines.push(x.line);}return `${imports.length?`from zebjus import ${imports.join(", ")}\n\n`:""}${lines.join("\n")}${lines.length?"\n":""}`;}
function stripGeneratedBlock(source){const A="# === ZEBJUS CIRCUIT AUTO-GENERATED START ===",B="# === ZEBJUS CIRCUIT AUTO-GENERATED END ===",re=new RegExp(A.replace(/[.*+?^${}()|[\]\\]/g,"\\$&")+"[\\s\\S]*?"+B.replace(/[.*+?^${}()|[\]\\]/g,"\\$&")+"\\n?","g");return String(source||"").replace(re,"").replace(/\n{3,}/g,"\n\n");}
function topLevelWhileIndex(source){const lines=String(source||"").split(/\r?\n/);for(let i=0;i<lines.length;i++)if(/^while\s+True\s*:\s*(?:#.*)?$/.test(lines[i]))return i;return -1;}
function applyGeneratedBlock(source,generated){const A="# === ZEBJUS CIRCUIT AUTO-GENERATED START ===",B="# === ZEBJUS CIRCUIT AUTO-GENERATED END ===",block=`${A}\n${String(generated||"").trim()}\n${B}`;let clean=stripGeneratedBlock(source).replace(/\s+$/g,"");const lines=clean.split(/\r?\n/),idx=topLevelWhileIndex(clean);if(idx>=0){const before=lines.slice(0,idx).join("\n").replace(/\s+$/g,""),after=lines.slice(idx).join("\n");return `${before}${before?"\n\n":""}${block}\n\n${after}\n`;}return `${clean}${clean?"\n\n":""}${block}\n`;}
function saveDesign(d){const n=normalizeDesign(d);n.updatedAt=new Date().toISOString();localStorage.setItem(STORAGE,JSON.stringify(n));publishDesign(n);return n;}
function loadDesign(){try{const raw=localStorage.getItem(STORAGE)||localStorage.getItem(LEGACY_STORAGE)||"null",d=normalizeDesign(JSON.parse(raw));if(!localStorage.getItem(STORAGE))localStorage.setItem(STORAGE,JSON.stringify(d));return d;}catch(_){return newDesign();}}
function syncToMain(d){const code=generatePython(d),src=localStorage.getItem(CODE_KEY)||"",out=applyGeneratedBlock(src,code);localStorage.setItem(CODE_KEY,out);localStorage.setItem("zebjus.lab.circuit.lastGenerated",code);try{globalThis.dispatchEvent?.(new StorageEvent("storage",{key:CODE_KEY,newValue:out}));}catch(_){try{globalThis.dispatchEvent?.(new CustomEvent("zebjus-circuit-code",{detail:{code:out}}));}catch(__){}}return out;}
g.ZebjusCircuit={VERSION:"6.8.1",STORAGE,LEGACY_STORAGE,CODE_KEY,CHANNEL,newDesign,normalizeDesign,addComponent,removeComponent,connect,disconnect,connectionFor,compatible,canUsePin,autoWireComponent,autoWireAll,validateDesign,generatePython,applyGeneratedBlock,saveDesign,loadDesign,syncToMain,onDesignChange,boardInfo,componentMeta,setProperty,setBridgeCapabilities,getCapabilities,i2cBus,spiBus,allocateUARTPorts,allocateSPIBuses};
})(globalThis);
