(function(){
"use strict";
const L=ZebjusCircuitLibrary,C=ZebjusCircuit,$=id=>document.getElementById(id);
let d=C.loadDesign(),zoom=.8,selection=null,pendingPort=null,focusWires=false;
const undoStack=[],redoStack=[],MAX_HISTORY=60;
const colors={adc:'#c084fc',digitalIn:'#60a5fa',counterIn:'#38bdf8',echoIn:'#38bdf8',digitalOut:'#f59e0b',pwmOut:'#fb7185',bidir:'#eab308',i2cSda:'#22d3ee',i2cScl:'#2dd4bf',uartRx:'#a78bfa',uartTx:'#8b5cf6',spiSck:'#f97316',spiMiso:'#84cc16',spiMosi:'#65a30d',spiCs:'#eab308',power:'#ef4444',gnd:'#64748b'};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function toast(s){const e=$('toast');e.textContent=s;e.hidden=false;clearTimeout(toast.t);toast.t=setTimeout(()=>e.hidden=true,1900)}
function snap(){return JSON.stringify(C.normalizeDesign(d))}
function setHistoryButtons(){$('undoBtn').disabled=!undoStack.length;$('redoBtn').disabled=!redoStack.length}
function pushUndo(before){if(!before||before===snap())return;undoStack.push(before);if(undoStack.length>MAX_HISTORY)undoStack.shift();redoStack.length=0;setHistoryButtons()}
function persist(){C.saveDesign(d)}
function mutate(fn,{sync=true}={}){const before=snap();fn();pushUndo(before);persist();renderAll();if(sync)maybeSync()}
function undo(){if(!undoStack.length)return;redoStack.push(snap());d=C.normalizeDesign(JSON.parse(undoStack.pop()));persist();selection=null;pendingPort=null;renderAll();maybeSync();setHistoryButtons()}
function redo(){if(!redoStack.length)return;undoStack.push(snap());d=C.normalizeDesign(JSON.parse(redoStack.pop()));persist();selection=null;pendingPort=null;renderAll();maybeSync();setHistoryButtons()}
function meta(c){return L.BY_TYPE[c?.type]}
function boardVisual(id){const sig=L.BOARD_PINS.filter(p=>p.gpio!=null),i=sig.findIndex(p=>p.id===id);if(i>=0){const half=Math.ceil(sig.length/2),right=i>=half,row=right?i-half:i,x=right?282:58,y=42+row*28;return {x,y,left:x,top:y,right}}const power={GND:{x:115,y:338,left:115,top:338},'3V3':{x:170,y:338,left:170,top:338},'5V':{x:225,y:338,left:225,top:338}};return power[id]||power['3V3']}
function initFilters(){const f=$('groupFilter');[...new Set(L.COMPONENTS.map(x=>x.group))].sort().forEach(x=>{const o=document.createElement('option');o.value=o.textContent=x;f.appendChild(o)})}
function addFromShelf(type,x=null,y=null){mutate(()=>{const n=d.components.length,c=C.addComponent(d,type,x??(90+(n%4)*220),y??(90+Math.floor(n/4)*190));selection={kind:'component',id:c.id};});closeDrawers()}
function renderShelf(){const q=$('componentSearch').value.toLowerCase(),grp=$('groupFilter').value,items=L.COMPONENTS.filter(x=>(!q||(x.label+' '+x.type+' '+x.description).toLowerCase().includes(q))&&(!grp||x.group===grp));$('componentCount').textContent=`${L.COMPONENTS.length} devices`;$('componentShelf').innerHTML=items.map(x=>`<div class="shelf-item" role="button" tabindex="0" draggable="true" data-type="${esc(x.type)}" title="${esc(x.description)}"><img src="${x.asset2d}" alt="${esc(x.label)}"><b>${esc(x.label)}</b><span>${esc(x.group)}</span></div>`).join('');$('componentShelf').querySelectorAll('.shelf-item').forEach(e=>{e.addEventListener('dragstart',ev=>{ev.dataTransfer.effectAllowed='copy';ev.dataTransfer.setData('text/zebjus-component',e.dataset.type)});e.addEventListener('click',()=>addFromShelf(e.dataset.type));e.addEventListener('keydown',ev=>{if(ev.key==='Enter'||ev.key===' '){ev.preventDefault();addFromShelf(e.dataset.type)}})})}
function renderBoard(){const b=$('boardNode');b.style.left=d.board.x+'px';b.style.top=d.board.y+'px';const caps=C.getCapabilities();$('boardPorts').innerHTML=L.BOARD_PINS.map(p=>{const q=boardVisual(p.id),available=p.gpio==null||caps.gpioOut.includes(p.gpio)||caps.gpioIn.includes(p.gpio)||caps.adc1.includes(p.gpio);return `<button class="port board-port pin-hotspot ${q.right?'right':''} ${p.bootSensitive?'boot-pin':''}" style="left:${q.left}px;top:${q.top}px" data-board-pin="${p.id}" ${available?'':'disabled'} title="${esc(p.label)} · ${(p.caps||[]).join(', ')}${p.bootSensitive?' · BOOT-SENSITIVE':''}"><span>${p.id}</span></button>`}).join('');$('boardPorts').querySelectorAll('.board-port').forEach(e=>e.onclick=ev=>{ev.stopPropagation();if(pendingPort)connectBoard(e);else{selection={kind:'boardPin',id:e.dataset.boardPin};renderInspector()}})}
function componentTransform(c){return `rotate(${Number(c.rotation)||0}deg) scaleX(${c.flipX?-1:1}) scaleY(${c.flipY?-1:1})`}
function renderComponents(){const layer=$('componentLayer');layer.innerHTML=d.components.map(c=>{const m=meta(c),n=Math.max(1,m.ports.length);return `<div class="component-node ${selection?.kind==='component'&&selection.id===c.id?'selected':''}" data-component-id="${esc(c.id)}" style="left:${c.x}px;top:${c.y}px"><div class="node-drag-handle"><span>${esc(m.group)}</span><b>${esc(c.id)}</b></div><div class="component-title" title="${esc(m.label)}">${esc(m.label)}</div><div class="component-visual-shell"><div class="component-visual" style="transform:${componentTransform(c)}"><img src="${m.asset2d}" alt="${esc(m.label)}">${m.ports.map((p,i)=>`<button class="component-port pin-hotspot ${pendingPort?.componentId===c.id&&pendingPort?.port===p.name?'selected':''}" style="left:${((i+1)/(n+1))*100}%;top:83.5%" data-component="${esc(c.id)}" data-port="${esc(p.name)}" title="${esc(p.label)} · ${esc(p.kind)}"></button>`).join('')}</div></div><div class="component-pin-legend">${m.ports.map(p=>`<span>${esc(p.label)}</span>`).join('')}</div></div>`}).join('');layer.querySelectorAll('.component-node').forEach(node=>node.addEventListener('pointerdown',ev=>{if(ev.target.closest('.pin-hotspot'))return;selection={kind:'component',id:node.dataset.componentId};renderInspector();renderComponents();startDragComponent(ev,node.dataset.componentId)}));layer.querySelectorAll('.component-port').forEach(e=>e.onclick=ev=>{ev.stopPropagation();pendingPort={componentId:e.dataset.component,port:e.dataset.port};selection={kind:'component',id:e.dataset.component};renderComponents();showCompatible();renderInspector()})}
function startDragComponent(ev,id){if(ev.button!==undefined&&ev.button!==0)return;const c=d.components.find(x=>x.id===id);if(!c)return;ev.preventDefault();const before=snap(),sx=ev.clientX,sy=ev.clientY,ox=c.x,oy=c.y;const mv=e=>{c.x=Math.max(0,Math.min(d.width-230,ox+(e.clientX-sx)/zoom));c.y=Math.max(0,Math.min(d.height-220,oy+(e.clientY-sy)/zoom));renderComponents();renderWires()};const up=()=>{window.removeEventListener('pointermove',mv);window.removeEventListener('pointerup',up);c.x=Math.round(c.x/10)*10;c.y=Math.round(c.y/10)*10;renderComponents();renderWires();pushUndo(before);persist();maybeSync()};window.addEventListener('pointermove',mv);window.addEventListener('pointerup',up,{once:true})}
function startBoardDrag(ev){if(ev.button!==undefined&&ev.button!==0)return;ev.preventDefault();const before=snap(),sx=ev.clientX,sy=ev.clientY,ox=d.board.x,oy=d.board.y;const mv=e=>{d.board.x=Math.max(0,Math.min(d.width-340,ox+(e.clientX-sx)/zoom));d.board.y=Math.max(0,Math.min(d.height-430,oy+(e.clientY-sy)/zoom));renderBoard();renderWires()};const up=()=>{window.removeEventListener('pointermove',mv);window.removeEventListener('pointerup',up);d.board.x=Math.round(d.board.x/10)*10;d.board.y=Math.round(d.board.y/10)*10;renderBoard();renderWires();pushUndo(before);persist()};window.addEventListener('pointermove',mv);window.addEventListener('pointerup',up,{once:true})}
function startCanvasResize(ev){if(ev.button!==undefined&&ev.button!==0)return;const before=snap(),sx=ev.clientX,sy=ev.clientY,ow=d.width,oh=d.height;const mv=e=>{d.width=Math.max(1400,Math.round((ow+(e.clientX-sx)/zoom)/50)*50);d.height=Math.max(900,Math.round((oh+(e.clientY-sy)/zoom)/50)*50);renderCanvasSize();renderWires()};const up=()=>{window.removeEventListener('pointermove',mv);window.removeEventListener('pointerup',up);pushUndo(before);persist()};window.addEventListener('pointermove',mv);window.addEventListener('pointerup',up,{once:true})}
function showCompatible(){document.querySelectorAll('.board-port').forEach(e=>{e.classList.remove('compatible','invalid');if(!pendingPort)return;const c=d.components.find(x=>x.id===pendingPort.componentId),p=meta(c)?.ports.find(x=>x.name===pendingPort.port);if(!c||!p)return;const r=C.canUsePin(d,c,p,e.dataset.boardPin);e.classList.add(r.ok?'compatible':'invalid')});$('wireHint').hidden=!pendingPort}
function connectBoard(e){if(!pendingPort)return;try{mutate(()=>{C.connect(d,pendingPort.componentId,pendingPort.port,e.dataset.boardPin);pendingPort=null});toast('Wire connected')}catch(err){toast(err.message)}}
function stagePoint(el){if(!el)return null;const r=el.getBoundingClientRect(),s=$('canvasStage').getBoundingClientRect();return {x:(r.left+r.width/2-s.left)/zoom,y:(r.top+r.height/2-s.top)/zoom}}
function posForComponentPort(c,pn){return stagePoint(document.querySelector(`.component-port[data-component="${CSS.escape(c.id)}"][data-port="${CSS.escape(pn)}"]`))||{x:c.x+95,y:c.y+150}}
function posForBoardPin(id){return stagePoint(document.querySelector(`.board-port[data-board-pin="${CSS.escape(id)}"]`))||(()=>{const q=boardVisual(id);return {x:d.board.x+q.x,y:d.board.y+q.y}})()}
function wirePath(a,b,i){const dx=b.x-a.x,dy=b.y-a.y,len=Math.max(1,Math.hypot(dx,dy)),offset=((i%9)-4)*6,px=-dy/len*offset,py=dx/len*offset;const c1={x:a.x+dx*.34+px,y:a.y+dy*.10+py},c2={x:a.x+dx*.66+px,y:a.y+dy*.90+py};return {d:`M ${a.x} ${a.y} C ${c1.x} ${c1.y}, ${c2.x} ${c2.y}, ${b.x} ${b.y}`,x:a.x+dx*.52+px,y:a.y+dy*.5+py}}
function renderWires(){const svg=$('wireLayer'),groups=[];d.connections.forEach((w,i)=>{const c=d.components.find(x=>x.id===w.componentId);if(!c)return;const a=posForComponentPort(c,w.port),b=posForBoardPin(w.boardPin),p=wirePath(a,b,i),sel=selection?.kind==='wire'&&selection.id===w.id;groups.push(`<g class="wire-group ${focusWires&&!sel?'dim':''} ${sel?'selected':''}" data-wire="${esc(w.id)}"><path class="wire-hit" d="${p.d}"/><path class="wire-under" d="${p.d}"/><path class="wire-main" style="stroke:${colors[w.kind]||'#7dd3fc'}" d="${p.d}"/><text class="wire-label" x="${p.x}" y="${p.y}">${esc(w.port)}→${esc(w.boardPin)}</text></g>`)});svg.innerHTML=groups.join('');svg.querySelectorAll('.wire-hit').forEach(e=>e.onclick=()=>{selection={kind:'wire',id:e.parentNode.dataset.wire};renderInspector();renderWires()})}
function issues(){const x=C.validateDesign(d),box=$('issueList'),err=x.filter(i=>i.level==='error').length,warn=x.filter(i=>i.level==='warning').length;$('issueCount').textContent=`${err} error${err===1?'':'s'} · ${warn} warning${warn===1?'':'s'}`;box.innerHTML=x.length?x.map(i=>`<div class="issue ${i.level}">${esc(i.message)}</div>`).join(''):'<div class="ok-message">No circuit issues detected.</div>';$('designStatus').textContent=err?'CHECK WIRING':warn?'VALID + WARNINGS':'VALID';return x}
function propertyControl(c,s){const v=c.properties?.[s.key];if(s.type==='select')return `<select class="property-control" data-prop="${esc(s.key)}">${(s.options||[]).map(o=>`<option value="${esc(o)}" ${String(o)===String(v)?'selected':''}>${esc(o)}</option>`).join('')}</select>`;if(s.type==='checkbox')return `<input class="property-control" data-prop="${esc(s.key)}" type="checkbox" ${v?'checked':''}>`;const shown=s.type==='hex'?'0x'+Number(v).toString(16).toUpperCase():v;return `<input class="property-control" data-prop="${esc(s.key)}" type="${s.type==='number'?'number':'text'}" value="${esc(shown)}" ${s.min!=null?`min="${s.min}"`:''} ${s.max!=null?`max="${s.max}"`:''} ${s.step!=null?`step="${s.step}"`:''}>`}
function bindPropertyInputs(c){$('inspector').querySelectorAll('[data-prop]').forEach(el=>el.addEventListener('change',()=>{const key=el.dataset.prop,s=meta(c).properties.find(x=>x.key===key);let value=el.type==='checkbox'?el.checked:el.value;if(s.type==='hex'){value=String(value).trim();value=value.toLowerCase().startsWith('0x')?parseInt(value,16):Number(value)}const busChange=key==='bus'&&(c.type==='I2C'||c.type==='I2CDevice'||c.type==='LCD1602'||c.type==='MPU6050'||c.type==='SPI');try{mutate(()=>{C.setProperty(d,c.id,key,value);if(busChange){const kinds=c.type==='SPI'?new Set(['spiSck','spiMiso','spiMosi','spiCs']):new Set(['i2cSda','i2cScl']);d.connections=d.connections.filter(w=>!(w.componentId===c.id&&kinds.has(w.kind)));C.autoWireComponent(d,c.id)}});toast(`${s.label} updated`)}catch(e){toast(e.message);renderInspector()}}))}
function renderInspector(){const box=$('inspector'),empty=$('inspectorEmpty');if(!selection){empty.hidden=false;box.hidden=true;$('selectionKind').textContent='Nothing selected';return}empty.hidden=true;box.hidden=false;if(selection.kind==='component'){const c=d.components.find(x=>x.id===selection.id),m=c&&meta(c);if(!c||!m){selection=null;return renderInspector()}$('selectionKind').textContent=c.id;const propHtml=(m.properties||[]).length?`<div class="ins-group"><div class="ins-group-title">Component Settings</div>${m.properties.map(s=>`<div class="property-row"><label>${esc(s.label)}</label>${propertyControl(c,s)}</div>`).join('')}</div>`:'';box.innerHTML=`<div class="ins-row"><b>${esc(m.label)}</b><span>${esc(m.description)}</span></div>${m.ports.map(p=>{const w=C.connectionFor(d,c.id,p.name);return `<div class="ins-row"><b>${esc(p.label)}</b><span>${esc(p.kind)} · ${w?esc(w.boardPin):'NOT CONNECTED'}${p.optional?' · optional':''}</span></div>`}).join('')}${propHtml}<div class="ins-group"><div class="ins-group-title">Orientation</div><div class="orientation-tools"><button data-orient="left">↺ 90°</button><button data-orient="right">↻ 90°</button><button data-orient="flipX">⇋ Flip H</button><button data-orient="flipY">⇵ Flip V</button></div><div class="property-note">Artwork and physical pin holes rotate/flip. Labels and text stay upright.</div></div>`;bindPropertyInputs(c);box.querySelectorAll('[data-orient]').forEach(btn=>btn.onclick=()=>{mutate(()=>{const cc=d.components.find(x=>x.id===c.id);if(btn.dataset.orient==='left')cc.rotation=(Number(cc.rotation||0)+270)%360;else if(btn.dataset.orient==='right')cc.rotation=(Number(cc.rotation||0)+90)%360;else if(btn.dataset.orient==='flipX')cc.flipX=!cc.flipX;else if(btn.dataset.orient==='flipY')cc.flipY=!cc.flipY});toast('Component orientation updated')})}else if(selection.kind==='wire'){const w=d.connections.find(x=>x.id===selection.id);$('selectionKind').textContent='Wire';box.innerHTML=w?`<div class="ins-row"><b>${esc(w.componentId)}.${esc(w.port)}</b><span>${esc(w.boardPin)} · ${esc(w.kind)}</span></div><div class="property-note">Delete removes only this connection.</div>`:''}else if(selection.kind==='boardPin'){const p=L.BY_PIN[selection.id];$('selectionKind').textContent=selection.id;box.innerHTML=p?`<div class="ins-row"><b>${esc(p.label)}</b><span>${esc((p.caps||[]).join(' · '))}</span></div>${p.bootSensitive?'<div class="issue warning">Boot-sensitive GPIO. Prefer another pin unless the device specifically needs this input.</div>':''}`:''}}
function renderCanvasSize(){$('canvasSizeLabel').textContent=`${d.width}×${d.height}`;const s=$('canvasStage');s.style.width=d.width+'px';s.style.height=d.height+'px';const w=$('canvasWorld');w.style.width=Math.ceil(d.width*zoom)+'px';w.style.height=Math.ceil(d.height*zoom)+'px';const svg=$('wireLayer');svg.setAttribute('width',d.width);svg.setAttribute('height',d.height);svg.setAttribute('viewBox',`0 0 ${d.width} ${d.height}`)}
function renderAll(){renderCanvasSize();renderBoard();renderComponents();renderWires();issues();renderInspector();showCompatible();$('designName').textContent=d.name;setHistoryButtons()}
function maybeSync(){if($('autoSyncToggle').checked&&!C.validateDesign(d).some(i=>i.level==='error'))try{C.syncToMain(d)}catch(_){}}
function setZoom(z,anchor=null){const v=$('canvasViewport'),old=zoom,next=Math.max(.35,Math.min(1.8,z));let px=0,py=0,wx=0,wy=0;if(anchor){const r=v.getBoundingClientRect();px=anchor.clientX-r.left;py=anchor.clientY-r.top;wx=(v.scrollLeft+px)/old;wy=(v.scrollTop+py)/old}zoom=next;$('canvasStage').style.transform=`scale(${zoom})`;$('canvasWorld').style.width=Math.ceil(d.width*zoom)+'px';$('canvasWorld').style.height=Math.ceil(d.height*zoom)+'px';$('zoomRange').value=Math.round(zoom*100);$('zoomLabel').textContent=Math.round(zoom*100)+'%';if(anchor){v.scrollLeft=Math.max(0,wx*zoom-px);v.scrollTop=Math.max(0,wy*zoom-py)}}
function viewportCenter(){const r=$('canvasViewport').getBoundingClientRect();return {clientX:r.left+r.width/2,clientY:r.top+r.height/2}}
function startCanvasPan(ev){if(ev.button!==0&&ev.button!==1)return;if(ev.target.closest('button,input,select,.component-node,.board-node,.wire-group,.canvas-resize-handle'))return;ev.preventDefault();const v=$('canvasViewport'),sx=ev.clientX,sy=ev.clientY,sl=v.scrollLeft,st=v.scrollTop;v.classList.add('panning');const mv=e=>{v.scrollLeft=sl-(e.clientX-sx);v.scrollTop=st-(e.clientY-sy)};const up=()=>{window.removeEventListener('pointermove',mv);window.removeEventListener('pointerup',up);v.classList.remove('panning')};window.addEventListener('pointermove',mv);window.addEventListener('pointerup',up,{once:true})}
function tidy(){mutate(()=>{d.components.forEach((c,i)=>{c.x=80+(i%4)*215;c.y=90+Math.floor(i/4)*195});d.board.x=Math.max(970,80+Math.min(4,d.components.length)*215);d.board.y=250})}
function closeDrawers(){$('leftPanel').classList.remove('open');$('shelfPanel').classList.remove('open')}
async function loadKitCapabilities(){const badge=$('capabilityBadge');try{if(!window.ZebjusKit)return;const known=window.ZebjusKit.loadKnown().sort((a,b)=>(b.lastSeen||0)-(a.lastSeen||0));if(!known.length)return;const k=new window.ZebjusKit.KitClient(),x=known[0];k.name=x.name;k.ipHint=x.ip||'';k.chipId=String(x.chipId||'');await k.connect(k.name,k.ipHint);const info=await k.bridgeInfo();C.setBridgeCapabilities(info);badge.textContent=`Kit ${info.version||'bridge'} profile`;badge.title=`Capabilities read from ${x.name}`;renderAll()}catch(_){badge.textContent='Firmware v2.5.0 profile'}}
initFilters();renderShelf();renderAll();setZoom(zoom);loadKitCapabilities();
$('componentSearch').oninput=renderShelf;$('groupFilter').onchange=renderShelf;
$('canvasStage').ondragover=e=>{e.preventDefault();e.dataTransfer.dropEffect='copy'};$('canvasStage').ondrop=e=>{e.preventDefault();const t=e.dataTransfer.getData('text/zebjus-component');if(!t)return;const r=$('canvasStage').getBoundingClientRect();addFromShelf(t,(e.clientX-r.left)/zoom,(e.clientY-r.top)/zoom)};
$('canvasViewport').addEventListener('pointerdown',startCanvasPan);$('canvasViewport').addEventListener('wheel',e=>{e.preventDefault();setZoom(zoom*Math.exp(-e.deltaY*.0015),{clientX:e.clientX,clientY:e.clientY})},{passive:false});$('canvasViewport').addEventListener('dblclick',e=>{if(!e.target.closest('.component-node,.board-node,.wire-group'))$('fitBtn').click()});
document.querySelector('.board-drag').onpointerdown=startBoardDrag;$('canvasResizeHandle').onpointerdown=startCanvasResize;
$('autoWireBtn').onclick=()=>{let errs=[];mutate(()=>{errs=C.autoWireAll(d)});toast(errs.length?`${errs.length} component(s) need manual pins`:'Auto wiring complete')};$('validateBtn').onclick=()=>{const x=issues();toast(x.length?`${x.length} design note(s)`:'Circuit valid')};$('syncBtn').onclick=()=>{try{C.syncToMain(d);toast('main.py circuit block updated before LIVE loop')}catch(e){toast(e.message)}};
$('saveBtn').onclick=()=>{persist();toast('Circuit saved')};$('loadBtn').onclick=()=>{d=C.loadDesign();selection=null;pendingPort=null;undoStack.length=redoStack.length=0;renderAll();toast('Circuit reloaded')};$('newCircuitBtn').onclick=()=>{if(confirm('Clear the circuit?'))mutate(()=>{d=C.newDesign();selection=null;pendingPort=null})};$('tidyBtn').onclick=tidy;
$('undoBtn').onclick=undo;$('redoBtn').onclick=redo;
$('deleteBtn').onclick=()=>{if(!selection)return;mutate(()=>{if(selection.kind==='component')C.removeComponent(d,selection.id);else if(selection.kind==='wire')C.disconnect(d,selection.id);selection=null;pendingPort=null})};$('focusBtn').onclick=()=>{focusWires=!focusWires;$('focusBtn').classList.toggle('active',focusWires);renderWires()};
$('expandCanvasBtn').onclick=()=>mutate(()=>{d.width+=600;d.height+=400},{sync:false});$('zoomRange').oninput=e=>setZoom(Number(e.target.value)/100,viewportCenter());$('zoomInBtn').onclick=()=>setZoom(zoom+.1,viewportCenter());$('zoomOutBtn').onclick=()=>setZoom(zoom-.1,viewportCenter());$('fitBtn').onclick=()=>{const v=$('canvasViewport');setZoom(Math.min((v.clientWidth-20)/d.width,(v.clientHeight-20)/d.height,.95));v.scrollTo(0,0)};
$('wireToolBtn').onclick=()=>toast('Click a component pin, then a highlighted board pin.');$('selectToolBtn').onclick=()=>{pendingPort=null;showCompatible();renderComponents()};
$('leftPanelToggle').onclick=()=>{$('leftPanel').classList.toggle('open');$('shelfPanel').classList.remove('open')};$('shelfPanelToggle').onclick=()=>{$('shelfPanel').classList.toggle('open');$('leftPanel').classList.remove('open')};
window.addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='z'){e.preventDefault();e.shiftKey?redo():undo()}else if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='y'){e.preventDefault();redo()}else if(e.key==='Escape'){pendingPort=null;selection=null;closeDrawers();renderAll()}else if((e.key==='Delete'||e.key==='Backspace')&&selection&&!/INPUT|TEXTAREA|SELECT/.test(document.activeElement?.tagName||'')){$('deleteBtn').click()}});
if(C.onDesignChange)C.onDesignChange(next=>{d=next;selection=null;pendingPort=null;renderAll()});else window.addEventListener('storage',e=>{if(e.key===C.STORAGE){d=C.loadDesign();selection=null;pendingPort=null;renderAll()}});
})();
