(function(){
"use strict";
const L=ZebjusCircuitLibrary,C=ZebjusCircuit,$=id=>document.getElementById(id),esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
let d=C.loadDesign(),zoom=.85;
function toast(s){const e=$("toast");e.textContent=s;e.hidden=false;clearTimeout(toast.t);toast.t=setTimeout(()=>e.hidden=true,1600)}
function closePanels(){$("componentsPanel").classList.remove("open");$("checkPanel").classList.remove("open")}
function syncIfValid(){if(!C.validateDesign(d).some(x=>x.level==="error"))try{C.syncToMain(d)}catch(_){}}
function persist(opts={}){C.saveDesign(d);if(opts.sync!==false)syncIfValid()}
function shelf(){const q=$("search").value.toLowerCase();$("count").textContent=L.COMPONENTS.length;$("shelf").innerHTML='<div class="shelf">'+L.COMPONENTS.filter(m=>(m.label+" "+m.type+" "+m.group).toLowerCase().includes(q)).map(m=>'<button data-type="'+esc(m.type)+'">'+esc(m.label)+"<small>"+esc(m.group)+"</small></button>").join("")+"</div>";$("shelf").querySelectorAll("button").forEach(b=>b.onclick=()=>{const c=C.addComponent(d,b.dataset.type,120+(d.components.length%5)*245,120+Math.floor(d.components.length/5)*150);try{C.autoWireComponent(d,c.id)}catch(_){}persist();render();closePanels();toast("Component added")})}
function boardPinPos(id){const pins=L.BOARD_PINS,signals=pins.filter(p=>p.gpio!=null),i=signals.findIndex(p=>p.id===id),bx=d.board.x,by=d.board.y;if(i>=0){const half=Math.ceil(signals.length/2),right=i>=half,row=right?i-half:i;return{x:bx+(right?320:0),y:by+58+row*31,side:right?"right":"left",top:58+row*31}}const order=["3V3","5V","GND"],idx=Math.max(0,order.indexOf(id));return{x:bx+105+idx*55,y:by+660,side:"power",top:640+idx*24}}
function renderBoard(){const pins=L.BOARD_PINS,b=$("boardSymbol");b.style.left=d.board.x+"px";b.style.top=d.board.y+"px";b.innerHTML=pins.map(p=>{const q=boardPinPos(p.id),cls=q.side==="right"?"right":q.side==="left"?"left":"power",style=q.side==="right"||q.side==="left"?"top:"+q.top+"px":"left:"+(48+pins.filter(x=>x.gpio==null).indexOf(p)*72)+"px;bottom:42px";return'<span class="sch-pin '+cls+" "+(p.bootSensitive?"boot":"")+'" style="'+style+'" title="'+esc((p.caps||[]).join(", "))+'">'+esc(p.id)+"</span>"}).join("");b.onpointerdown=startBoardDrag}
function componentPortPos(c,port){const m=L.BY_TYPE[c.type],i=Math.max(0,m.ports.findIndex(p=>p.name===port));return{x:c.x+195,y:c.y+42+i*13}}
function render(){const sheet=$("sheet");sheet.style.width=d.width+"px";sheet.style.height=d.height+"px";$("schWorld").style.width=Math.ceil(d.width*zoom)+"px";$("schWorld").style.height=Math.ceil(d.height*zoom)+"px";$("wireSvg").setAttribute("viewBox","0 0 "+d.width+" "+d.height);$("wireSvg").setAttribute("width",d.width);$("wireSvg").setAttribute("height",d.height);renderBoard();$("nodes").innerHTML=d.components.map(c=>{const m=L.BY_TYPE[c.type],pins=m.ports.map(p=>{const w=C.connectionFor(d,c.id,p.name);return'<span class="pin-line"><strong>'+esc(p.label)+"</strong><span>"+(w?esc(w.boardPin):"—")+"</span></span>"}).join("");return'<div class="sch-node" data-id="'+esc(c.id)+'" style="left:'+c.x+"px;top:"+c.y+'px"><b>'+esc(m.label)+'</b><span class="node-id">'+esc(c.id)+"</span>"+pins+"</div>"}).join("");$("nodes").querySelectorAll(".sch-node").forEach(n=>n.onpointerdown=e=>startDrag(e,n.dataset.id));const paths=[];d.connections.forEach((w,i)=>{const c=d.components.find(x=>x.id===w.componentId);if(!c)return;const a=componentPortPos(c,w.port),b=boardPinPos(w.boardPin),lane=80+(i%12)*18,mid=Math.min(b.x-36,Math.max(a.x+38,a.x+lane)),path="M"+a.x+","+a.y+" L"+mid+","+a.y+" L"+mid+","+b.y+" L"+b.x+","+b.y;paths.push('<path class="sch-under" d="'+path+'"/><path class="sch-wire" d="'+path+'"/><text class="sch-label" x="'+(mid+4)+'" y="'+((a.y+b.y)/2)+'">'+esc(w.port)+"→"+esc(w.boardPin)+"</text>")});$("wireSvg").innerHTML=paths.join("");const is=C.validateDesign(d),errors=is.filter(x=>x.level==="error").length,warnings=is.filter(x=>x.level==="warning").length;$("issues").innerHTML=is.length?is.map(x=>'<div class="issue '+x.level+'">'+esc(x.message)+"</div>").join(""):'<p class="ok">No circuit issues.</p>';$("issueCount").textContent=errors+"E · "+warnings+"W";$("status").textContent=errors?"CHECK WIRING":warnings?"VALID + WARNINGS":"VALID";$("pinSummary").innerHTML=L.BOARD_PINS.map(p=>'<span title="'+esc((p.caps||[]).join(", "))+'">'+esc(p.id)+"</span>").join("")}
function startDrag(ev,id){if(ev.button!==undefined&&ev.button!==0)return;ev.preventDefault();const c=d.components.find(x=>x.id===id);if(!c)return;const sx=ev.clientX,sy=ev.clientY,ox=c.x,oy=c.y;const mv=e=>{c.x=Math.max(0,Math.min(d.width-210,ox+(e.clientX-sx)/zoom));c.y=Math.max(0,Math.min(d.height-120,oy+(e.clientY-sy)/zoom));render()};const up=()=>{window.removeEventListener("pointermove",mv);window.removeEventListener("pointerup",up);c.x=Math.round(c.x/10)*10;c.y=Math.round(c.y/10)*10;render();persist()};window.addEventListener("pointermove",mv);window.addEventListener("pointerup",up,{once:true})}
function startBoardDrag(ev){if(ev.button!==undefined&&ev.button!==0)return;ev.preventDefault();const sx=ev.clientX,sy=ev.clientY,ox=d.board.x,oy=d.board.y;const mv=e=>{d.board.x=Math.max(0,Math.min(d.width-320,ox+(e.clientX-sx)/zoom));d.board.y=Math.max(0,Math.min(d.height-720,oy+(e.clientY-sy)/zoom));render()};const up=()=>{window.removeEventListener("pointermove",mv);window.removeEventListener("pointerup",up);d.board.x=Math.round(d.board.x/10)*10;d.board.y=Math.round(d.board.y/10)*10;render();persist({sync:false})};window.addEventListener("pointermove",mv);window.addEventListener("pointerup",up,{once:true})}
function setZoom(z,anchor=null){const v=$("viewport"),old=zoom,next=Math.max(.35,Math.min(1.5,z));let px=0,py=0,wx=0,wy=0;if(anchor){const r=v.getBoundingClientRect();px=anchor.clientX-r.left;py=anchor.clientY-r.top;wx=(v.scrollLeft+px)/old;wy=(v.scrollTop+py)/old}zoom=next;$("sheet").style.transform="scale("+zoom+")";$("schWorld").style.width=Math.ceil(d.width*zoom)+"px";$("schWorld").style.height=Math.ceil(d.height*zoom)+"px";$("zoomLabel").textContent=Math.round(zoom*100)+"%";if(anchor){v.scrollLeft=Math.max(0,wx*zoom-px);v.scrollTop=Math.max(0,wy*zoom-py)}}
function viewportCenter(){const r=$("viewport").getBoundingClientRect();return{clientX:r.left+r.width/2,clientY:r.top+r.height/2}}
function startPan(ev){if(ev.button!==0&&ev.button!==1)return;if(ev.target.closest("button,a,input,.sch-node,.sch-board"))return;ev.preventDefault();const v=$("viewport"),sx=ev.clientX,sy=ev.clientY,sl=v.scrollLeft,st=v.scrollTop;v.classList.add("panning");const mv=e=>{v.scrollLeft=sl-(e.clientX-sx);v.scrollTop=st-(e.clientY-sy)};const up=()=>{window.removeEventListener("pointermove",mv);window.removeEventListener("pointerup",up);v.classList.remove("panning")};window.addEventListener("pointermove",mv);window.addEventListener("pointerup",up,{once:true})}
function fit(){const v=$("viewport");setZoom(Math.min((v.clientWidth-24)/d.width,(v.clientHeight-24)/d.height,.95));v.scrollTo(0,0)}
function tidy(){d.components.forEach((c,i)=>{c.x=90+(i%5)*240;c.y=100+Math.floor(i/5)*145});d.board={x:Math.max(900,d.width-500),y:260};persist();render();toast("Schematic tidied")}
shelf();render();setZoom(zoom);$("search").oninput=shelf;$("saveBtn").onclick=()=>{persist();toast("Saved")};$("reloadBtn").onclick=()=>{d=C.loadDesign();render();toast("Reloaded")};$("syncBtn").onclick=()=>{try{C.syncToMain(d);toast("main.py updated")}catch(e){toast(e.message)}};$("expandBtn").onclick=()=>{d.width+=500;d.height+=350;persist({sync:false});render();toast("Sheet expanded")};$("fitBtn").onclick=fit;$("zoomInBtn").onclick=()=>setZoom(zoom+.1,viewportCenter());$("zoomOutBtn").onclick=()=>setZoom(zoom-.1,viewportCenter());$("tidyBtn").onclick=tidy;$("componentsToggle").onclick=()=>{$("componentsPanel").classList.toggle("open");$("checkPanel").classList.remove("open")};$("checkToggle").onclick=()=>{$("checkPanel").classList.toggle("open");$("componentsPanel").classList.remove("open")};$("viewport").addEventListener("pointerdown",startPan);$("viewport").addEventListener("wheel",e=>{e.preventDefault();setZoom(zoom*Math.exp(-e.deltaY*.0015),{clientX:e.clientX,clientY:e.clientY})},{passive:false});window.addEventListener("keydown",e=>{if(e.key==="Escape")closePanels()});if(C.onDesignChange)C.onDesignChange(next=>{d=next;render()});else window.addEventListener("storage",e=>{if(e.key===C.STORAGE||e.key===C.LEGACY_STORAGE){d=C.loadDesign();render()}});
})();
