(function(){
"use strict";
const L=ZebjusCircuitLibrary,C=ZebjusCircuit,R=window.ZebjusWireRouter,$=id=>document.getElementById(id),esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
let d=C.loadDesign(),zoom=.85,simulator=null,simulationFrame={running:false,components:[]};
function toast(s){const e=$("toast");e.textContent=s;e.hidden=false;clearTimeout(toast.t);toast.t=setTimeout(()=>e.hidden=true,1600)}
function closePanels(){$("componentsPanel").classList.remove("open");$("checkPanel").classList.remove("open")}
function syncIfValid(){if(!C.validateDesign(d).some(x=>x.level==="error"))try{C.syncToMain(d)}catch(_){}}
function persist(opts={}){C.saveDesign(d);if(opts.sync!==false)syncIfValid()}
function shelf(){const q=$("search").value.toLowerCase();$("count").textContent=L.COMPONENTS.length;$("shelf").innerHTML='<div class="shelf">'+L.COMPONENTS.filter(m=>(m.label+" "+m.type+" "+m.group).toLowerCase().includes(q)).map(m=>'<button data-type="'+esc(m.type)+'">'+esc(m.label)+"<small>"+esc(m.group)+"</small></button>").join("")+"</div>";$("shelf").querySelectorAll("button").forEach(b=>b.onclick=()=>{const c=C.addComponent(d,b.dataset.type,120+(d.components.length%5)*245,120+Math.floor(d.components.length/5)*150);try{C.autoWireComponent(d,c.id)}catch(_){}persist();render();closePanels();toast("Component added")})}
function boardPinPos(id){const p=L.BY_PIN[id],v=p?.visual||{x:210,y:588,side:"power"};return{x:d.board.x+Number(v.x),y:d.board.y+Number(v.y),side:v.side||"power",left:Number(v.x),top:Number(v.y)}}
function renderBoard(){const b=$("boardSymbol");b.style.left=d.board.x+"px";b.style.top=d.board.y+"px";b.innerHTML='<span class="board-subtitle">38-PIN EXPANSION · 12V / 5V / 3.3V</span>'+L.BOARD_PINS.map(p=>{const q=boardPinPos(p.id),cls=q.side==="right"?"right":q.side==="left"?"left":"power";return'<span class="sch-pin '+cls+" "+(p.bootSensitive?"boot ":"")+(p.reserved?"reserved":"")+'" style="left:'+q.left+'px;top:'+q.top+'px" title="'+esc((p.caps||[]).join(", "))+'">'+esc(p.label||p.id)+"</span>"}).join("");b.onpointerdown=startBoardDrag}
function componentPortPos(c,port){const m=L.BY_TYPE[c.type],i=Math.max(0,m.ports.findIndex(p=>p.name===port));return{x:c.x+195,y:c.y+46+i*14}}
function schematicPins(){const pins=[];d.components.forEach(c=>(L.BY_TYPE[c.type]?.ports||[]).forEach(port=>pins.push({...componentPortPos(c,port.name),key:`component:${c.id}:${port.name}`,radius:14})));L.BOARD_PINS.forEach(pin=>pins.push({...boardPinPos(pin.id),key:`board:${pin.id}`,radius:18}));return pins}
function schematicBoardLead(id,end){const side=boardPinPos(id).side,gap=32;if(side==="left")return{x:end.x-gap,y:end.y};if(side==="right")return{x:end.x+gap,y:end.y};return{x:end.x,y:end.y+gap}}
function schematicWireFlow(kind){if(["adc","digitalIn","counterIn","echoIn","uartTx","spiMiso","gnd"].includes(kind))return"to-board";if(["i2cSda","bidir"].includes(kind))return"bidirectional";return"from-board"}
function renderSchematicWires(){const paths=[],labels=[],labelBoxes=[],occupied=[],pins=schematicPins(),bounds={minX:8,minY:8,maxX:d.width-8,maxY:d.height-8};d.connections.forEach((w,i)=>{const c=d.components.find(x=>x.id===w.componentId);if(!c)return;const a=componentPortPos(c,w.port),b=boardPinPos(w.boardPin),startKey=`component:${c.id}:${w.port}`,endKey=`board:${w.boardPin}`,route=R.route({start:a,end:b,startLead:{x:a.x+32,y:a.y},endLead:schematicBoardLead(w.boardPin,b),pins,exclude:[startKey,endKey],occupied,index:i,bounds,keepout:16}),flow=schematicWireFlow(w.kind),text=flow==="from-board"?w.boardPin+"→"+w.port:flow==="bidirectional"?w.port+"↔"+w.boardPin:w.port+"→"+w.boardPin,label=R.labelPlacement({points:route.points,text,pins,exclude:[startKey,endKey],labels:labelBoxes,index:i,bounds});occupied.push(route.points);labelBoxes.push(label);paths.push('<g class="sch-wire-group" data-component="'+esc(w.componentId)+'" data-flow="'+flow+'" data-pin-conflicts="'+route.conflicts.length+'" data-wire-overlaps="'+(route.overlaps||0)+'" data-wire-crossings="'+(route.crossings||0)+'" data-start-key="'+esc(startKey)+'" data-end-key="'+esc(endKey)+'"><path class="sch-under" d="'+route.d+'"/><path class="sch-wire" d="'+route.d+'"/></g>');labels.push('<g class="sch-label-group"><rect class="sch-label-bg" x="'+label.x+'" y="'+label.y+'" width="'+label.width+'" height="'+label.height+'" rx="7"/><text class="sch-label" text-anchor="middle" x="'+label.textX+'" y="'+label.textY+'">'+esc(text)+"</text></g>")});$("wireSvg").innerHTML=paths.join("")+'<g class="sch-label-layer" aria-hidden="true">'+labels.join("")+"</g>"}
function paintSimulationFrame(frame){simulationFrame=frame||{running:false,components:[]};const running=!!simulationFrame.running,byId=new Map((simulationFrame.components||[]).map(x=>[x.id,x]));document.body.classList.toggle("simulation-running",running);$("nodes").querySelectorAll(".sch-node").forEach(n=>{const state=byId.get(n.dataset.id),on=running&&!!state;n.classList.toggle("simulating",on);n.classList.toggle("sim-active",on&&!!state.active);n.style.setProperty("--sim-level",(Number(state?.level)||0)+"%");const badge=n.querySelector(".sch-sim-badge");if(badge)badge.textContent=on?String(state.value||"ACTIVE"):"READY"});$("wireSvg").querySelectorAll(".sch-wire-group").forEach(group=>{const state=byId.get(group.dataset.component);group.classList.toggle("flowing",running&&!!state?.active);group.style.setProperty("--flow-speed",Math.max(.28,1.05-(Number(state?.level)||0)/145)+"s")});const btn=$("runSimulationBtn");btn.classList.toggle("running",running);btn.textContent=running?"■ Stop Simulation":"▶ Run Simulation";if(running)$("status").textContent="SIMULATION"}
function render(){const sheet=$("sheet");sheet.style.width=d.width+"px";sheet.style.height=d.height+"px";$("schWorld").style.width=Math.ceil(d.width*zoom)+"px";$("schWorld").style.height=Math.ceil(d.height*zoom)+"px";$("wireSvg").setAttribute("viewBox","0 0 "+d.width+" "+d.height);$("wireSvg").setAttribute("width",d.width);$("wireSvg").setAttribute("height",d.height);renderBoard();$("nodes").innerHTML=d.components.map(c=>{const m=L.BY_TYPE[c.type],pins=m.ports.map(p=>{const w=C.connectionFor(d,c.id,p.name);return'<span class="pin-line"><strong>'+esc(p.label)+"</strong><span>"+(w?esc(w.boardPin):"—")+"</span></span>"}).join("");return'<div class="sch-node" data-id="'+esc(c.id)+'" data-type="'+esc(c.type)+'" style="left:'+c.x+"px;top:"+c.y+'px"><b>'+esc(m.label)+'</b><span class="node-id">'+esc(c.id)+'</span><span class="sch-sim-badge">READY</span>'+pins+"</div>"}).join("");$("nodes").querySelectorAll(".sch-node").forEach(n=>n.onpointerdown=e=>startDrag(e,n.dataset.id));renderSchematicWires();const is=C.validateDesign(d),errors=is.filter(x=>x.level==="error").length,warnings=is.filter(x=>x.level==="warning").length;$("issues").innerHTML=is.length?is.map(x=>'<div class="issue '+x.level+'">'+esc(x.message)+"</div>").join(""):'<p class="ok">No circuit issues.</p>';$("issueCount").textContent=errors+"E · "+warnings+"W";$("status").textContent=errors?"CHECK WIRING":warnings?"VALID + WARNINGS":"VALID";$("pinSummary").innerHTML=L.BOARD_PINS.map(p=>'<span title="'+esc((p.caps||[]).join(", "))+'">'+esc(p.label||p.id)+"</span>").join("");paintSimulationFrame(simulationFrame)}
function toggleSimulation(){if(simulator.isRunning()){simulator.stop();render();toast("Simulation stopped");return}const errors=C.validateDesign(d).filter(x=>x.level==="error");if(errors.length){render();toast("Fix "+errors.length+" wiring error(s) before simulation");return}try{C.syncToMain(d)}catch(_){}simulator.start();toast("Working simulation started")}
function startDrag(ev,id){if(ev.button!==undefined&&ev.button!==0)return;ev.preventDefault();const c=d.components.find(x=>x.id===id);if(!c)return;const sx=ev.clientX,sy=ev.clientY,ox=c.x,oy=c.y;const mv=e=>{c.x=Math.max(0,Math.min(d.width-210,ox+(e.clientX-sx)/zoom));c.y=Math.max(0,Math.min(d.height-120,oy+(e.clientY-sy)/zoom));render()};const up=()=>{window.removeEventListener("pointermove",mv);window.removeEventListener("pointerup",up);c.x=Math.round(c.x/10)*10;c.y=Math.round(c.y/10)*10;render();persist()};window.addEventListener("pointermove",mv);window.addEventListener("pointerup",up,{once:true})}
function startBoardDrag(ev){if(ev.button!==undefined&&ev.button!==0)return;ev.preventDefault();const sx=ev.clientX,sy=ev.clientY,ox=d.board.x,oy=d.board.y;const mv=e=>{d.board.x=Math.max(0,Math.min(d.width-420,ox+(e.clientX-sx)/zoom));d.board.y=Math.max(0,Math.min(d.height-650,oy+(e.clientY-sy)/zoom));render()};const up=()=>{window.removeEventListener("pointermove",mv);window.removeEventListener("pointerup",up);d.board.x=Math.round(d.board.x/10)*10;d.board.y=Math.round(d.board.y/10)*10;render();persist({sync:false})};window.addEventListener("pointermove",mv);window.addEventListener("pointerup",up,{once:true})}
function setZoom(z,anchor=null){const v=$("viewport"),old=zoom,next=Math.max(.35,Math.min(1.5,z));let px=0,py=0,wx=0,wy=0;if(anchor){const r=v.getBoundingClientRect();px=anchor.clientX-r.left;py=anchor.clientY-r.top;wx=(v.scrollLeft+px)/old;wy=(v.scrollTop+py)/old}zoom=next;$("sheet").style.transform="scale("+zoom+")";$("schWorld").style.width=Math.ceil(d.width*zoom)+"px";$("schWorld").style.height=Math.ceil(d.height*zoom)+"px";$("zoomLabel").textContent=Math.round(zoom*100)+"%";if(anchor){v.scrollLeft=Math.max(0,wx*zoom-px);v.scrollTop=Math.max(0,wy*zoom-py)}}
function viewportCenter(){const r=$("viewport").getBoundingClientRect();return{clientX:r.left+r.width/2,clientY:r.top+r.height/2}}
function startPan(ev){if(ev.button!==0&&ev.button!==1)return;if(ev.target.closest("button,a,input,.sch-node,.sch-board"))return;ev.preventDefault();const v=$("viewport"),sx=ev.clientX,sy=ev.clientY,sl=v.scrollLeft,st=v.scrollTop;v.classList.add("panning");const mv=e=>{v.scrollLeft=sl-(e.clientX-sx);v.scrollTop=st-(e.clientY-sy)};const up=()=>{window.removeEventListener("pointermove",mv);window.removeEventListener("pointerup",up);v.classList.remove("panning")};window.addEventListener("pointermove",mv);window.addEventListener("pointerup",up,{once:true})}
function fit(){const v=$("viewport");setZoom(Math.min((v.clientWidth-24)/d.width,(v.clientHeight-24)/d.height,.95));v.scrollTo(0,0)}
function tidy(){d.components.forEach((c,i)=>{c.x=90+(i%5)*240;c.y=100+Math.floor(i/5)*145});d.board={x:Math.max(900,d.width-560),y:260};persist();render();toast("Schematic tidied")}
if(!R)throw new Error("Pin-safe wire router did not load");
if(!window.ZebjusCircuitSimulator)throw new Error("Circuit simulator library did not load");
simulator=window.ZebjusCircuitSimulator.create({getDesign:()=>d,onFrame:paintSimulationFrame});
shelf();render();setZoom(zoom);$("search").oninput=shelf;$("saveBtn").onclick=()=>{persist();toast("Saved")};$("reloadBtn").onclick=()=>{d=C.loadDesign();render();toast("Reloaded")};$("syncBtn").onclick=()=>{try{C.syncToMain(d);toast("main.py updated")}catch(e){toast(e.message)}};$("runSimulationBtn").onclick=toggleSimulation;$("expandBtn").onclick=()=>{d.width+=500;d.height+=350;persist({sync:false});render();toast("Sheet expanded")};$("fitBtn").onclick=fit;$("zoomInBtn").onclick=()=>setZoom(zoom+.1,viewportCenter());$("zoomOutBtn").onclick=()=>setZoom(zoom-.1,viewportCenter());$("tidyBtn").onclick=tidy;$("componentsToggle").onclick=()=>{$("componentsPanel").classList.toggle("open");$("checkPanel").classList.remove("open")};$("checkToggle").onclick=()=>{$("checkPanel").classList.toggle("open");$("componentsPanel").classList.remove("open")};$("viewport").addEventListener("pointerdown",startPan);$("viewport").addEventListener("wheel",e=>{e.preventDefault();setZoom(zoom*Math.exp(-e.deltaY*.0015),{clientX:e.clientX,clientY:e.clientY})},{passive:false});window.addEventListener("keydown",e=>{if(e.key==="Escape")closePanels()});window.addEventListener("pageshow",render);window.addEventListener("resize",render);document.addEventListener("visibilitychange",()=>{if(document.visibilityState==="visible")requestAnimationFrame(render)});window.addEventListener("pagehide",()=>simulator.stop());if(C.onDesignChange)C.onDesignChange(next=>{d=next;render()});else window.addEventListener("storage",e=>{if(e.key===C.STORAGE||e.key===C.LEGACY_STORAGE){d=C.loadDesign();render()}});
})();
