"use strict";
const fs=require("fs"),http=require("http"),net=require("net"),os=require("os"),path=require("path"),{spawn,spawnSync}=require("child_process");
const ROOT=__dirname;
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
function assert(ok,data){if(!ok)throw new Error(typeof data==="string"?data:JSON.stringify(data));}
function executable(name){const r=spawnSync("sh",["-c",`command -v ${name}`],{encoding:"utf8"});return r.status===0?r.stdout.trim():"";}
function chromePath(){if(process.env.CHROMIUM&&fs.existsSync(process.env.CHROMIUM))return process.env.CHROMIUM;const known=["/Applications/Google Chrome.app/Contents/MacOS/Google Chrome","/Applications/Chromium.app/Contents/MacOS/Chromium","/Applications/Microsoft Edge.app/Contents/MacOS/Microsoft Edge",process.env.LOCALAPPDATA&&path.join(process.env.LOCALAPPDATA,"Google","Chrome","Application","chrome.exe"),process.env.PROGRAMFILES&&path.join(process.env.PROGRAMFILES,"Google","Chrome","Application","chrome.exe")].filter(Boolean);for(const p of known)if(fs.existsSync(p))return p;for(const n of ["chromium","chromium-browser","google-chrome","google-chrome-stable","microsoft-edge"]){const p=executable(n);if(p)return p;}return "";}
function freePort(){return new Promise((resolve,reject)=>{const s=net.createServer();s.once("error",reject);s.listen(0,"127.0.0.1",()=>{const p=s.address().port;s.close(()=>resolve(p));});});}
function mime(file){return file.endsWith(".html")?"text/html":file.endsWith(".js")?"text/javascript":file.endsWith(".css")?"text/css":file.endsWith(".svg")?"image/svg+xml":"application/octet-stream";}
function staticServer(){return http.createServer((req,res)=>{let rel;try{rel=decodeURIComponent(new URL(req.url,"http://local").pathname).replace(/^\/+/,"")||"index.html";}catch(_){res.writeHead(400).end();return;}const file=path.resolve(ROOT,rel);if(!file.startsWith(ROOT+path.sep)){res.writeHead(403).end();return;}fs.readFile(file,(e,b)=>{if(e){res.writeHead(404).end();return;}res.writeHead(200,{"Content-Type":mime(file),"Cache-Control":"no-store"});res.end(b);});});}

(async()=>{
  const chrome=chromePath();
  if(!chrome){const msg="Circuit browser UI regression SKIP: Chromium/Chrome executable is not installed in this environment";if(process.env.ZEBJUS_REQUIRE_BROWSER==="1")throw new Error(msg);console.log(msg);process.exitCode=77;return;}
  const httpPort=await freePort(),dbgPort=await freePort(),server=staticServer();
  await new Promise((resolve,reject)=>server.listen(httpPort,"127.0.0.1",e=>e?reject(e):resolve()));
  const profile=fs.mkdtempSync(path.join(os.tmpdir(),"zebjus-chrome-"));
  const proc=spawn(chrome,["--headless=new","--no-sandbox","--disable-gpu","--disable-dev-shm-usage","--remote-allow-origins=*",`--remote-debugging-port=${dbgPort}`,`--user-data-dir=${profile}`,"about:blank"],{stdio:"ignore"});
  let ws;
  try{
    let info=null;
    for(let i=0;i<100&&!info;i++){try{const r=await fetch(`http://127.0.0.1:${dbgPort}/json/list`);const pages=await r.json();if(pages.length)info=pages[0];}catch(_){}if(!info)await sleep(100);}
    assert(info,"Chromium DevTools did not start");ws=new WebSocket(info.webSocketDebuggerUrl);
    await new Promise((resolve,reject)=>{const t=setTimeout(()=>reject(new Error("DevTools WebSocket timeout")),5000);ws.addEventListener("open",()=>{clearTimeout(t);resolve();},{once:true});ws.addEventListener("error",()=>{clearTimeout(t);reject(new Error("DevTools WebSocket error"));},{once:true});});
    let seq=0;const pending=new Map(),events=[];
    ws.addEventListener("message",e=>{const m=JSON.parse(String(e.data));if(m.id&&pending.has(m.id)){const p=pending.get(m.id);pending.delete(m.id);m.error?p.reject(new Error(JSON.stringify(m.error))):p.resolve(m.result||{});}else events.push(m);});
    const call=(method,params={})=>new Promise((resolve,reject)=>{const id=++seq;pending.set(id,{resolve,reject});ws.send(JSON.stringify({id,method,params}));});
    const evaljs=async expression=>{const r=await call("Runtime.evaluate",{expression,returnByValue:true,awaitPromise:true});if(r.exceptionDetails)throw new Error(r.exceptionDetails.text||"JS exception");return r.result?.value;};
    const waitReady=async()=>{for(let i=0;i<100;i++){try{if(await evaljs("document.readyState") === "complete"&&await evaljs('typeof ZebjusCircuit!=="undefined"'))return;}catch(_){}await sleep(100);}throw new Error("Page did not become ready");};
    await call("Runtime.enable");await call("Page.enable");await call("Log.enable");
    await call("Emulation.setDeviceMetricsOverride",{width:1440,height:900,deviceScaleFactor:1,mobile:false});
    await call("Page.navigate",{url:`http://127.0.0.1:${httpPort}/circuit.html`});await waitReady();
    const desktop=await evaljs(`(()=>{const q=s=>document.querySelector(s),r=e=>{const x=e.getBoundingClientRect();return{x:x.x,y:x.y,w:x.width,h:x.height,right:x.right,bottom:x.bottom}};const a=r(q('.left-panel')),b=r(q('.designer-main')),c=r(q('.shelf-panel')),inp=r(q('#componentSearch')),tabs=[...document.querySelectorAll('.workspace-tab')];return{version:ZebjusCircuit.VERSION,shelf:q('#componentShelf').children.length,total:ZebjusCircuitLibrary.COMPONENTS.length,physicalPins:ZebjusCircuitLibrary.PHYSICAL_PIN_COUNT,left:a,main:b,shelfPanel:c,input:inp,overflow:document.documentElement.scrollWidth-window.innerWidth,resize:!!q('#canvasResizeHandle'),undo:!!q('#undoBtn'),props:!!q('.inspector-section'),run:!!q('#runSimulationBtn'),customBoard:q('#boardNode img')?.src.includes('zebjus-custom-board-38pin-2d.svg'),tabs:tabs.map(x=>x.textContent.trim()),active:tabs.find(x=>x.matches('[aria-current="page"]'))?.textContent.trim(),threeD:!!q('#view3dBtn')||[...document.images].some(x=>x.src.includes('-3d.svg')),world:!!q('#canvasWorld')}})()`);
    assert(desktop.version==="6.8.0"&&desktop.shelf===desktop.total&&desktop.total===80&&desktop.physicalPins===38,desktop);assert(desktop.left.right<=desktop.main.x+1&&desktop.main.right<=desktop.shelfPanel.x+1,desktop);assert(desktop.input.w<=desktop.shelfPanel.w&&desktop.resize&&desktop.undo&&desktop.props&&desktop.world&&desktop.run&&desktop.customBoard,desktop);assert(desktop.tabs.join('|')==="Python Lab|Circuit Design|Schematic"&&desktop.active==="Circuit Design"&&!desktop.threeD,desktop);
    await evaljs(`document.querySelector('.shelf-item[data-type="DHT11"]').click();document.querySelector('#autoWireBtn').click();`);await sleep(200);
    const state=await evaljs(`({count:ZebjusCircuit.loadDesign().components.length,errors:ZebjusCircuit.validateDesign(ZebjusCircuit.loadDesign()).filter(x=>x.level==='error').length,nodes:document.querySelectorAll('.component-node').length})`);assert(state.count>=1&&state.errors===0&&state.nodes>=1,state);
    const simulation=await evaljs(`(()=>{document.querySelector('#runSimulationBtn').click();return{running:document.body.classList.contains('simulation-running'),label:document.querySelector('#runSimulationBtn').textContent,wireZ:Number(getComputedStyle(document.querySelector('#wireLayer')).zIndex||0),nodeZ:getComputedStyle(document.querySelector('.component-node')).zIndex}})()`);assert(simulation.running&&simulation.label.includes('Stop')&&simulation.wireZ>=40,simulation);
    const interaction=await evaljs(`(()=>{const node=document.querySelector('.component-node'),wire=document.querySelector('.wire-main'),v=document.querySelector('#canvasViewport'),nr=node.getBoundingClientRect(),vr=v.getBoundingClientRect(),beforePath=wire?.getAttribute('d'),beforeZoom=parseInt(document.querySelector('#zoomLabel').textContent);node.dispatchEvent(new PointerEvent('pointerdown',{bubbles:true,button:0,clientX:nr.left+40,clientY:nr.top+20}));window.dispatchEvent(new PointerEvent('pointermove',{bubbles:true,button:0,clientX:nr.left+120,clientY:nr.top+70}));window.dispatchEvent(new PointerEvent('pointerup',{bubbles:true,button:0,clientX:nr.left+120,clientY:nr.top+70}));const afterPath=document.querySelector('.wire-main')?.getAttribute('d'),moved=ZebjusCircuit.loadDesign().components[0];v.dispatchEvent(new WheelEvent('wheel',{bubbles:true,cancelable:true,deltaY:-160,clientX:vr.left+vr.width/2,clientY:vr.top+vr.height/2}));const afterZoom=parseInt(document.querySelector('#zoomLabel').textContent);v.scrollLeft=200;v.scrollTop=150;const sl=v.scrollLeft,st=v.scrollTop;v.dispatchEvent(new PointerEvent('pointerdown',{bubbles:true,button:0,clientX:vr.left+180,clientY:vr.top+180}));window.dispatchEvent(new PointerEvent('pointermove',{bubbles:true,button:0,clientX:vr.left+120,clientY:vr.top+140}));window.dispatchEvent(new PointerEvent('pointerup',{bubbles:true,button:0,clientX:vr.left+120,clientY:vr.top+140}));return{wireFollow:!!beforePath&&beforePath!==afterPath,moved,zoomed:afterZoom>beforeZoom,panned:v.scrollLeft>sl||v.scrollTop>st,zoom:afterZoom}})()`);
    assert(interaction.wireFollow&&interaction.moved.x%10===0&&interaction.moved.y%10===0&&interaction.zoomed&&interaction.panned,interaction);
    await call("Emulation.setDeviceMetricsOverride",{width:390,height:844,deviceScaleFactor:1,mobile:true});await call("Page.reload",{ignoreCache:true});await waitReady();await sleep(200);
    const mobile=await evaljs(`(()=>{const cs=s=>getComputedStyle(document.querySelector(s)),r=s=>{const x=document.querySelector(s).getBoundingClientRect();return{x:x.x,w:x.width,right:x.right}};return{mobileBar:cs('.mobile-bar').display,leftTransform:cs('.left-panel').transform,shelfTransform:cs('.shelf-panel').transform,main:r('.designer-main'),vw:innerWidth,bodyScroll:document.documentElement.scrollWidth}})()`);
    assert(mobile.mobileBar!=="none"&&mobile.main.w>=360&&mobile.bodyScroll<=400,mobile);await evaljs(`document.querySelector('#shelfPanelToggle').click()`);
    const opened=await evaljs(`({open:document.querySelector('#shelfPanel').classList.contains('open'),x:document.querySelector('#shelfPanel').getBoundingClientRect().x,w:document.querySelector('#shelfPanel').getBoundingClientRect().width,vw:innerWidth})`);assert(opened.open&&opened.x<opened.vw&&opened.w<=opened.vw,opened);
    await call("Emulation.setDeviceMetricsOverride",{width:1365,height:800,deviceScaleFactor:1,mobile:false});await call("Page.navigate",{url:`http://127.0.0.1:${httpPort}/schematic.html`});await waitReady();await sleep(200);
    const sch=await evaljs(`({board:!!document.querySelector('#boardSymbol .sch-pin'),pins:document.querySelectorAll('#boardSymbol .sch-pin').length,w:parseInt(document.querySelector('#sheet').style.width),h:parseInt(document.querySelector('#sheet').style.height),status:document.querySelector('#status').textContent,version:ZebjusCircuit.VERSION,tabs:[...document.querySelectorAll('.workspace-tab')].map(x=>x.textContent.trim()),active:document.querySelector('.workspace-tab[aria-current="page"]')?.textContent.trim(),world:!!document.querySelector('#schWorld'),shared:ZebjusCircuit.loadDesign().components.length})`);
    assert(sch.version==="6.8.0"&&sch.board&&sch.pins===42&&sch.w>=1400&&sch.h>=900&&sch.world&&sch.shared>=1,sch);assert(sch.tabs.join('|')==="Python Lab|Circuit Design|Schematic"&&sch.active==="Schematic",sch);
    const bad=events.filter(e=>e.method==="Runtime.exceptionThrown").map(e=>e.params?.exceptionDetails?.text||"exception");assert(!bad.length,"Browser JS exceptions: "+JSON.stringify(bad));
    console.log("Circuit browser UI regression PASS: 80-part shelf + 38-pin custom board + front wires + working simulation + live drag/zoom/pan + shared schematic state");
  }finally{
    try{ws?.close();}catch(_){}try{proc.kill("SIGTERM");}catch(_){}await new Promise(r=>server.close(r));try{fs.rmSync(profile,{recursive:true,force:true});}catch(_){}
  }
})().catch(e=>{console.error(e.stack||e);process.exitCode=1;});
